# Generated by Django 5.2.5 on 2025-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_profile_phone_number_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
