# Generated by Django 5.2.5 on 2025-09-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_experience_profile_professional_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
    ]
