# Generated by Django 5.2.5 on 2025-09-24 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_meeting_id', models.CharField(max_length=20, unique=True)),
                ('participant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=60)),
                ('join_url', models.URLField()),
                ('start_url', models.URLField()),
                ('password', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participated_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
