# Generated by Django 5.2.5 on 2025-10-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif_chatapp', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_booking_notifications', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('client_messages', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='users.proffessional')),
            ],
        ),
    ]
