# Generated by Django 5.2.5 on 2025-10-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif_chatapp', '0003_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
